apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sdemo-group-binding
subjects:
- kind: Group
  name: k8s-demo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-read
  apiGroup: rbac.authorization.k8s.io
