apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8sdemo-group-binding
  namespace: k8s-demo
subjects:
- kind: Group
  name: k8s-demo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
