apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k8s-demo
  name: read-only
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
